#ifndef ERROR_CODES_H
#define ERROR_CODES_H
// --------

#include <limits.h>

// --------

enum ErrorCodes {

	ERROR_CODE_UNKNOWN_SYSTEM_ERROR = INT_MIN,

	ERROR_CODE_INTEGER_OVERFLOW,

	ERROR_CODE_MALLOC_FAILURE,
	ERROR_CODE_OPEN_FAILURE,

	ERROR_CODE_SDL_ERROR = -1,

	ERROR_CODE_SUCCESS = 0,

	ERROR_CODE_UNKNOWN_ERROR,

	ERROR_CODE_INVALID_STATE,
	ERROR_CODE_INVALID_ARGUMENT,

	ERROR_CODE_UNEXPECTED_EOF,
	ERROR_CODE_UNEXPECTED_CHARACTER,
	ERROR_CODE_UNEXPECTED_FOLLOW_UP_CHARACTER,

	ERROR_CODE_INSTRUMENT_BUFFER_OVERFLOW,

	ERROR_CODE_BAR_TOO_SHORT,
	ERROR_CODE_BAR_TOO_LONG,

};

// --------
#endif

